name: Daily Diploma Crawler

on:
  schedule:
    # Runs every day at 3PM UTC (15:00)
    - cron: '0 15 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run cron job
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        X_CONSUMER_KEY: ${{ secrets.X_CONSUMER_KEY }}
        X_CONSUMER_SECRET: ${{ secrets.X_CONSUMER_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        REDIS_BASE_URL: ${{ secrets.REDIS_BASE_URL }}
        REDIS_BEARER_KEY: ${{ secrets.REDIS_BEARER_KEY }}
      run: python3 cron_job.py
